# Generated by Django 4.2 on 2024-07-25 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sending_emails", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="next_day",
        ),
        migrations.AddField(
            model_name="mailing",
            name="next_time_mailing",
            field=models.DateTimeField(
                blank=True,
                help_text="Формат DD.MM.YYYY HH:MM:SS",
                null=True,
                verbose_name="Следующее время рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Формат DD.MM.YYYY HH:MM:SS",
                null=True,
                verbose_name="Конец рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Формат DD.MM.YYYY HH:MM:SS",
                verbose_name="Начало рассылки",
            ),
        ),
    ]
