# Generated by Django 4.2 on 2024-07-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sending_emails", "0003_mailingattempt_mailing_alter_mailing_mailing_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="massage",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="massage",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="subject_massage",
            new_name="subject_message",
        ),
    ]
