# Generated by Django 4.2 on 2024-07-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_emails", "0004_rename_massage_mailing_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="mail_response",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ответ почтового сервера",
            ),
        ),
    ]
